### ISSUE TITLE
node_runner.py実行時にエラー

### ISSUE THREAD

**Issue by zk1tty** [kiyomaro927/getcoordinate#2]
databaseに関して親切にお答えくださり、ありがとうございます。
README.mdに沿って実行してみたのですが、
node_runner.py実行時に以下のようなエラーが出て、調べてもわかりませんでした。

> $ python node_runner.py
> Traceback (most recent call last):
>   File "node_runner.py", line 1, in <module>
>     from parse_naturedata import ParseNatureData
>File"C:\Users\Username\DwangoWorks\ConnectivityVisualization\coordinates\getcoordinate\parse_naturedata.py", line 1, in <module>
>     import pandas as pd
>   File "C:\Users\Username\Anaconda2\Lib\site-packages\pandas\__init__.py", line 19, in <module>
>     "Missing required dependencies {0}".format(missing_dependencies))
> ImportError: Missing required dependencies ['numpy']
> 
実行環境は
・OS windows10
・python 2.7
です。

よろしくお願いいたします。

**Comment by zk1tty** [comment]
すみません、こちらで解決しました。
